site_name: Jiratag Commitizen
site_description: commit rules, semantic version, conventional commits

theme:
    name: 'material'

repo_name: cgutierrezpa/jiratag-commitizen
repo_url: https://github.com/cgutierrezpa/jiratag-commitizen
edit_uri: ""

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra